export const items = [
  {
    id: "i1",
    name: "Dosa",
    category: "tiffin",
    price: 100.0,
    image: "",
    descripton: "",
  },
  {
    id: "i2",
    name: "Idli",
    category: "tiffin",
    price: 70.0,
    image: "",
    descripton: "",
  },
  {
    id: "i3",
    name: "Rice",
    category: "main course",
    price: 100.0,
    image: "",
    descripton: "",
  },
  {
    id: "i4",
    name: "Chicken Lollypop",
    category: "starter",
    price: 120.0,
    image: "",
    descripton: "",
  },
  {
    id: "i5",
    name: "Mojito",
    category: "drinks",
    price: 120.0,
    image: "",
    descripton: "",
  },
];
